### ISSUE TITLE
Issues getting set up

### ISSUE THREAD

**Issue by 123kyle16** [jdhuang-csm/bayes-drt#10]
Hello! My name is Kyle Coughlin and I am working on a paper surveying multiple EIS-DRT methods. Your method is of great interest to me, but after trying both versions of your code I was unable to get set up. In version two I am not able to install cmdstan and in version one pystan fails to build. I believe these are issues with my proxy/company protections on my computer. Would you be able to produce some outputs for me? I can email you the generic data (Synthetic Zarc1 and Zarc2 with simulated error) and detail the outputs I would need.

I would appreciate it a lot!!!!

**Comment by jdhuang-csm** [comment]
Hi Kyle, I may be able to help you out if you just need some fitting results. Can you let me know how many spectra you are planning to analyze and exactly which outputs you're looking for?

**Comment by 123kyle16** [comment]
Hello! I want to analyze two spectra. I would like to see the same outputs as those in section one of the jupyter notebook:  Quick start and general recommendations.ipynb. But as applied to my data.

The attached spreadsheats are my two spectra. The first column is the frequencies, the second is the real portion of impedance evaluated at the frequency, and the third is the imaginary part.

**Comment by 123kyle16** [comment]
[Z_1_e_bayes.xlsx](https://github.com/jdhuang-csm/bayes-drt/files/11736235/Z_1_e_bayes.xlsx)
[Z_2_e_bayes.xlsx](https://github.com/jdhuang-csm/bayes-drt/files/11736236/Z_2_e_bayes.xlsx)

**Comment by 123kyle16** [comment]
Hello again! Just wanted to see if you saw my above reply.

**Comment by jdhuang-csm** [comment]
Hi Kyle, sorry, I'm really cramped on time right now. I can probably get to this within the next couple of weeks, but I'm also thinking ahead to potential draft revisions and/or follow-up analyses for which you might (very reasonably) need additional results. I think that the best solution might be to work with your system administrators to get cmdstan installed so that you can use the package yourself. If that's not a possibility, I will certainly try to get you the data that you need, but I can't make any promises on timing.

**Comment by 123kyle16** [comment]
Thank you so much for the reply! Sounds good. I will try to get cmdstan working.

**Comment by jdhuang-csm** [comment]
Hi Kyle, just a thought - you could alternatively try using my hybrid-drt package, which implements a similar model, instead of bayes-drt. hybrid-drt does not require any form of Stan interface (i.e. pystan or cmdstanpy).

**Comment by 123kyle16** [comment]
Jake:

Thank you so much! That package works for me, thank you so much!

I will make sure to send you my paper once its published. Your package and algorithm is one of the best ive found for DRT solving.

**Comment by jdhuang-csm** [comment]
That's great! I'll look forward to reading your paper.
