### ISSUE TITLE
no dataset '550C.0.5V.DTA' in the bayes-drt package

### ISSUE THREAD

**Issue by PushkarevAS** [jdhuang-csm/bayes-drt#11]
Hello!

It looks like there is no 550C.0.5V.DTA dataset, which is necessary to finish tutorial #1 Basis frequencies, initialization, and non-negativity constraint, point 2b.

Please make this dataset available.

Best regards,
Artem Pushkarev

**Comment by jdhuang-csm** [comment]
Hello, my apologies for the missing data. It should be available in the data/experimental folder now.

**Comment by PushkarevAS** [comment]
Thank you very much!

Best regards,
Artem Pushkarev
________________________________
От: Jake Huang ***@***.***>
Отправлено: 20 июня 2023 г. 15:19
Кому: jdhuang-csm/bayes-drt ***@***.***>
Копия: PushkarevAS ***@***.***>; Author ***@***.***>
Тема: Re: [jdhuang-csm/bayes-drt] no dataset '550C.0.5V.DTA' in the bayes-drt package (Issue #11)


Hello, my apologies for the missing data. It should be available in the data/experimental folder now.
