### ISSUE TITLE
Tutorial 1 - Error during HMC Fit

### ISSUE THREAD

**Issue by Rblack999** [jdhuang-csm/bayes-drt#4]
Hello. Great library you have here and I am very excited to try and use this library to fit and analyze my own data. I am running in a conda environment with all packages installed successfully, and have got to the point of running the first HMC fit simply following Tutorial 1. I obtain the following error below. I tried to look into it but honestly cannot find much. Any idea why this is the case?

# Sample the posterior distribution
start = time.time()
inv_hmc.bayes_fit(freq,Zc)
elapsed = time.time() - start
print('HMC sampling time: {:.2f} s'.format(elapsed))

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Blackr\Anaconda3\envs\DRT\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Blackr\Anaconda3\envs\DRT\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "stanfit4anon_model_5e41d7ccbb68c66e26beba2b6307db0c_8841332859592360126.pyx", line 373, in stanfit4anon_model_5e41d7ccbb68c66e26beba2b6307db0c_8841332859592360126._call_sampler_star
  File "stanfit4anon_model_5e41d7ccbb68c66e26beba2b6307db0c_8841332859592360126.pyx", line 406, in stanfit4anon_model_5e41d7ccbb68c66e26beba2b6307db0c_8841332859592360126._call_sampler
RuntimeError: no more scalars to read
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-11-768b38e1a049> in <module>
      1 # Sample the posterior distribution
      2 start = time.time()
----> 3 inv_hmc.bayes_fit(freq,Zc)
      4 elapsed = time.time() - start
      5 print('HMC sampling time: {:.2f} s'.format(elapsed))

~\Anaconda3\envs\DRT\lib\site-packages\bayes_drt-0.1-py3.7.egg\bayes_drt\inversion.py in bayes_fit(self, frequencies, Z, part, scale_Z, init_from_ridge, nonneg_drt, outliers, sigma_min, warmup, sample, chains, random_seed, inductance_scale, outlier_lambda, fitY, Yscale, SA, SASY)
    811                 # sample from posterior
    812 		self._sample_result = model.sampling(dat,warmup=warmup,iter=warmup+sample,chains=chains,seed=random_seed,init=init,
--> 813 								  control={'adapt_delta':0.9,'adapt_t0':10})
    814 
    815                 # extract coefficients

~\Anaconda3\envs\DRT\lib\site-packages\pystan\model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)
    776         call_sampler_args = izip(itertools.repeat(data), args_list, itertools.repeat(pars))
    777         call_sampler_star = self.module._call_sampler_star
--> 778         ret_and_samples = _map_parallel(call_sampler_star, call_sampler_args, n_jobs)
    779         samples = [smpl for _, smpl in ret_and_samples]
    780 

~\Anaconda3\envs\DRT\lib\site-packages\pystan\model.py in _map_parallel(function, args, n_jobs)
     83         try:
     84             pool = multiprocessing.Pool(processes=n_jobs)
---> 85             map_result = pool.map(function, args)
     86         finally:
     87             pool.close()

~\Anaconda3\envs\DRT\lib\multiprocessing\pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

~\Anaconda3\envs\DRT\lib\multiprocessing\pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

RuntimeError: no more scalars to read
----------------------------------------------------

I then tried the map fitting later on in the tutorial to see if that would work, and every time it causes the jupyter notebook kernal to just crash.

**Comment by jdhuang-csm** [comment]
Hi there, thanks for reporting this issue! I'm not sure at first glance what the issue is, but I'd definitely like to get this working for you. Can you try running the following code as a minimal test of the pystan sampling functionality?

```
import pystan as stan

model_code = '''
data {
    int<lower=0> N;
}
parameters {
    vector<lower=0>[N] x;
}
model {
    x ~ std_normal();
}
'''

sm = stan.StanModel(model_code=model_code)

data = {'N':100}
fit = sm.sampling(data,iter=100,chains=4)
```

If the above code throws an error, can you then try running the modified sampling call below (which should disable parallelization)?

`fit = sm.sampling(data,iter=100,chains=4,n_jobs=1)`

**Comment by Rblack999** [comment]
The above code appears to have run and completed just fine without an error. No need to run the modified sampling call.

**Comment by jdhuang-csm** [comment]
Ok, that's good. It seems there may be a problem with the precompiled Stan model. Can you try the following?
1. Navigate to `~\Anaconda3\envs\DRT\lib\site-packages\bayes_drt-0.1-py3.7.egg\bayes_drt\stan_model_files` and delete the file `Series_StanModel.pkl`.
2. Restart the kernel and re-run the tutorial code. This should force Stan to recompile the underlying model for the DRT. You should see a pystan message telling you that it's compiling the C++ code for the model when you import the package, which will take a couple minutes.

**Comment by Rblack999** [comment]
That seems to have worked! No issues now, and thanks for taking the time to help me figure that out.

**Comment by jdhuang-csm** [comment]
That's great! Unfortunately, you'll probably have to do the same with all the other .pkl files in the stan_model_files directory (but not the .txt files) - those models are used for other types of fits and will throw errors for other tutorials if they have the same issue. I'm going to update the setup.py file to exclude the precompiled .pkl files from the installation, so that the Stan models are always compiled on the user's computer to avoid this issue. Thanks for helping me find this - I think it would have caused issues for a lot of people.

**Comment by jdhuang-csm** [comment]
Updated MANIFEST.in and installation instructions to avoid this issue in the future.
