### ISSUE TITLE
Pickle5 compatibility with recent Python versions

### ISSUE THREAD

**Issue by rixjilli** [jdhuang-csm/bayes-drt#6]
I'm running Python 3.10.0, and am having an issue with Pickle5 working only through Python 3.7 (when I try to install the Inverter, I get the error "No module named 'pickle5'"). Is there a way to adapt this to work with more recent versions of python? The rest of my EIS code runs on 3.10, so it would be great to not have to switch.

Thanks for your help, this is a really useful package!

**Comment by jdhuang-csm** [comment]
Yes, absolutely - the package should use pickle, not pickle5 (I was running tests with pickle5 and accidentally pushed that to GitHub). I've replaced pickle5 with pickle in stan_models.py. Sorry about that, and thanks for catching it!

**Comment by michi-berry** [comment]
Hi I'm rixjilli's colleague and we working on this together. I've changed pickle5 to pickle in stan_models.py and everything seems to have compiled well. I'm running into an issue when I try to run Inverter. It doesn't like the load_pickle command. Is this a difference in how pickle and pickle5 are defined? Thank you so much for your help and sharing this code!

<img width="476" alt="image" src="https://user-images.githubusercontent.com/41810752/149022937-4c32b22b-b66e-415f-8ff0-2017c062badc.png">

**Comment by jdhuang-csm** [comment]
Hi, I haven't seen that error before. Can you provide the full error traceback? The EOFError suggests that the Inverter is trying to load an empty pickle file, which may indicate a problem with model compilation.

**Comment by michi-berry** [comment]
I'm so sorry! I actually just needed to redownload the original file. I must have made a change when trying to fix the issue. Thank you so much for your time!

**Comment by jdhuang-csm** [comment]
No problem! Feel free to leave a comment here if it turns out that it's still not working.
