### ISSUE TITLE
plot_distribution secondary x axis incorrect

### ISSUE THREAD

**Issue by wgardnerQS** [jdhuang-csm/bayes-drt#7]
I think the frequencies of the secondary x axes output by plot_distribution are incorrect.  The code under `if freq_axis:` of `plot_distribution` sets axes ticks and labels based on a fixed range of frequencies.

In a test case, substituting ax2 specification with below worked.  Apologies if I've misinterpreted

```
def freq2tau(x):
        return 1 / (2 * np.pi * x)

ax2 = ax.secondary_xaxis('top', functions=(freq2tau, freq2tau))`
```

**Comment by jdhuang-csm** [comment]
I think you're right - I wasn't aware of `secondary_xaxis`, so I put in a hacky workaround. That method will definitely save me time in the future! I will update the code soon when I have a little time. Thanks for reporting!

**Comment by jdhuang-csm** [comment]
Replaced manual frequency axis construction with `secondary_xaxis`.
