### ISSUE TITLE
TabError in inversion.py

### ISSUE THREAD

**Issue by wgardnerQS** [jdhuang-csm/bayes-drt#8]
`from bayes_drt.inversion import Inverter` with python 3.9.16 throws 

TabError: inconsistent use of tabs and spaces in indentation 

cause is line 1642 of inversion.py.  The line is indented with tabs.  Other lines in the file are indented with spaces.

**Comment by jdhuang-csm** [comment]
Thanks, this should be fixed by the latest commit.
